#!/usr/bin/env bash
# cb2000_orchestrator.sh — CB2000 driver interactive main menu.
#
# Manages environment configuration, Python venv, builds, and test sessions.
# Saves configuration to .cb2000_env (gitignored) so settings persist.
#
# Usage: ./scripts/cb2000_orchestrator.sh

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${PROJECT_ROOT}/.cb2000_env"
VENV_DIR="${PROJECT_ROOT}/scripts/venv"
SCRIPTS_DIR="${PROJECT_ROOT}/scripts"
LOG_ROOT_DEFAULT="${PROJECT_ROOT}/../dev_logs/sessions"

default_container_home() {
  if [[ "${HOME}" == */.ContainerConfigs/${DBX_NAME} ]]; then
    printf '%s' "${HOME}"
  elif [[ "${HOME}" == */.ContainerConfigs ]]; then
    printf '%s' "${HOME}/${DBX_NAME}"
  else
    printf '%s' "${HOME}/.ContainerConfigs/${DBX_NAME}"
  fi
}

# ─── Colors ───────────────────────────────────────────────────────────────────
if [[ -t 1 ]]; then
  C_BOLD='\033[1m'; C_CYAN='\033[0;36m'; C_GREEN='\033[0;32m'
  C_YELLOW='\033[0;33m'; C_RED='\033[0;31m'; C_RESET='\033[0m'
else
  C_BOLD=''; C_CYAN=''; C_GREEN=''; C_YELLOW=''; C_RED=''; C_RESET=''
fi

# ─── Load saved configuration ─────────────────────────────────────────────────
load_env() {
  if [[ -f "${ENV_FILE}" ]]; then
    # shellcheck source=/dev/null
    source "${ENV_FILE}"
  fi
  BUILD_TARGET="${BUILD_TARGET:-container}"
  DBX_NAME="${DBX_NAME:-canvasbio}"
  CB2000_LOG_ROOT="${CB2000_LOG_ROOT:-${LOG_ROOT_DEFAULT}}"

  if [[ "${BUILD_TARGET}" == "container" ]]; then
    local detected_root
    detected_root="$(default_container_home)/libfprint"
    CB2000_LIBFPRINT_ROOT="${CB2000_LIBFPRINT_ROOT:-${detected_root}}"
  else
    CB2000_LIBFPRINT_ROOT="${CB2000_LIBFPRINT_ROOT:-}"
  fi
}

save_env() {
  cat > "${ENV_FILE}" <<EOF
# CB2000 local configuration — generated by cb2000_orchestrator.sh
# Do not commit (listed in .gitignore).
BUILD_TARGET="${BUILD_TARGET}"
DBX_NAME="${DBX_NAME}"
CB2000_LIBFPRINT_ROOT="${CB2000_LIBFPRINT_ROOT}"
CB2000_LOG_ROOT="${CB2000_LOG_ROOT}"
EOF
  echo -e "${C_GREEN}Configuration saved to ${ENV_FILE}${C_RESET}"
}

# ─── State detection ──────────────────────────────────────────────────────────
venv_status() {
  if [[ -f "${VENV_DIR}/bin/activate" ]]; then
    echo -e "${C_GREEN}OK (scripts/venv/)${C_RESET}"
  else
    echo -e "${C_YELLOW}not created${C_RESET}"
  fi
}

libfprint_status() {
  local root="${CB2000_LIBFPRINT_ROOT:-}"
  if [[ -n "${root}" && -d "${root}/builddir" ]]; then
    echo -e "${C_GREEN}${root}${C_RESET}"
  elif [[ -n "${root}" ]]; then
    echo -e "${C_YELLOW}${root} (no builddir/)${C_RESET}"
  else
    echo -e "${C_YELLOW}not set${C_RESET}"
  fi
}

# ─── Header ───────────────────────────────────────────────────────────────────
print_header() {
  echo ""
  echo -e "${C_BOLD}${C_CYAN}╔══════════════════════════════════════╗${C_RESET}"
  echo -e "${C_BOLD}${C_CYAN}║  CB2000 Driver — Orchestrator v1.0  ║${C_RESET}"
  echo -e "${C_BOLD}${C_CYAN}╚══════════════════════════════════════╝${C_RESET}"
  echo ""
  echo -e "${C_BOLD}Current configuration:${C_RESET}"
  echo -e "  Build target : ${C_CYAN}${BUILD_TARGET}${C_RESET}"
  if [[ "${BUILD_TARGET}" == "container" ]]; then
    echo -e "  Container    : ${C_CYAN}${DBX_NAME}${C_RESET}"
  fi
  echo -e "  libfprint    : $(libfprint_status)"
  echo -e "  Python venv  : $(venv_status)"
  echo -e "  Log dir      : ${C_CYAN}${CB2000_LOG_ROOT}${C_RESET}"
  echo ""
  echo -e "${C_BOLD}Options:${C_RESET}"
  echo -e " ${C_CYAN}[1]${C_RESET} Configure environment (build target, container, libfprint path, log dir)"
  echo -e " ${C_CYAN}[2]${C_RESET} Create / update Python venv"
  echo -e " ${C_CYAN}[3]${C_RESET} Build: OpenCV helper (.so)"
  echo -e " ${C_CYAN}[4]${C_RESET} Build: libfprint driver"
  echo -e " ${C_CYAN}[5]${C_RESET} Full session  (build + enroll + verify)"
  echo -e " ${C_CYAN}[6]${C_RESET} Session without build (enroll + verify only)"
  echo -e " ${C_CYAN}[7]${C_RESET} Battery report"
  echo -e " ${C_CYAN}[Q]${C_RESET} Quit"
  echo ""
}

# ─── Option 1: Configure environment ──────────────────────────────────────────
configure_env() {
  echo ""
  echo -e "${C_BOLD}=== Configure Environment ===${C_RESET}"

  echo "Build target [container/host] (current: ${BUILD_TARGET}): "
  read -r -p "> " input_target
  input_target="${input_target:-${BUILD_TARGET}}"
  if [[ "${input_target}" != "container" && "${input_target}" != "host" ]]; then
    echo -e "${C_RED}Invalid value. Use 'container' or 'host'.${C_RESET}"
    return
  fi
  BUILD_TARGET="${input_target}"

  if [[ "${BUILD_TARGET}" == "container" ]]; then
    echo "Container name (current: ${DBX_NAME}): "
    read -r -p "> " input_dbx
    DBX_NAME="${input_dbx:-${DBX_NAME}}"

    local detected_root
    detected_root="$(default_container_home)/libfprint"
    echo "libfprint path (detected default: ${detected_root}): "
    read -r -p "> " input_root
    CB2000_LIBFPRINT_ROOT="${input_root:-${detected_root}}"
  else
    echo "libfprint path (must contain builddir/): "
    read -r -p "> " input_root
    if [[ -z "${input_root}" ]]; then
      echo -e "${C_RED}Path cannot be empty in host mode.${C_RESET}"
      return
    fi
    if [[ ! -d "${input_root}/builddir" ]]; then
      echo -e "${C_YELLOW}Warning: builddir/ not found at ${input_root}${C_RESET}"
    fi
    CB2000_LIBFPRINT_ROOT="${input_root}"
  fi

  echo "Log directory (current: ${CB2000_LOG_ROOT}): "
  read -r -p "> " input_logroot
  CB2000_LOG_ROOT="${input_logroot:-${CB2000_LOG_ROOT}}"

  save_env
}

# ─── Option 2: Python venv ────────────────────────────────────────────────────
setup_venv() {
  echo ""
  echo -e "${C_BOLD}=== Create / Update Python venv ===${C_RESET}"
  echo "Creating venv at ${VENV_DIR}..."
  python3 -m venv "${VENV_DIR}"
  echo "Installing dependencies from requirements.txt..."
  "${VENV_DIR}/bin/pip" install -q -r "${PROJECT_ROOT}/requirements.txt"
  echo -e "${C_GREEN}venv OK.${C_RESET}"
}

# ─── Option 3: Build OpenCV helper ────────────────────────────────────────────
build_opencv_helper() {
  echo ""
  echo -e "${C_BOLD}=== Build: OpenCV Helper (.so) ===${C_RESET}"
  local build_script="${SCRIPTS_DIR}/build_sigfm_opencv_helper.sh"

  if [[ "${BUILD_TARGET}" == "container" ]]; then
    export DBX_NAME CB2000_LIBFPRINT_ROOT
    distrobox enter "${DBX_NAME}" -- bash -lc \
      "CB2000_LIBFPRINT_ROOT='${CB2000_LIBFPRINT_ROOT}' bash '${build_script}'"
  else
    export CB2000_LIBFPRINT_ROOT
    bash "${build_script}"
  fi
}

# ─── Option 4: Build libfprint driver ─────────────────────────────────────────
build_libfprint() {
  echo ""
  echo -e "${C_BOLD}=== Build: libfprint Driver ===${C_RESET}"
  local libfprint_root="${CB2000_LIBFPRINT_ROOT}"
  local driver_dir="${libfprint_root}/libfprint/drivers/canvasbio_cb2000"

  if [[ "${BUILD_TARGET}" == "container" ]]; then
    distrobox enter "${DBX_NAME}" -- bash -lc "
      cp '${PROJECT_ROOT}/src/canvasbio_cb2000.c' '${driver_dir}/'
      cp '${PROJECT_ROOT}/src/cb2000_sigfm_matcher.c' '${driver_dir}/'
      cp '${PROJECT_ROOT}/src/cb2000_sigfm_matcher.h' '${driver_dir}/'
      cd '${libfprint_root}' && ninja -C builddir
    "
  else
    local setup_script="${SCRIPTS_DIR}/setup-libfprint.sh"
    if [[ ! -d "${libfprint_root}" ]]; then
      echo -e "${C_YELLOW}libfprint not found at ${libfprint_root} — cloning, integrating, and building...${C_RESET}"
      LIBFPRINT_DIR="${libfprint_root}" bash "${setup_script}" --clone --integrate --build
    elif [[ ! -d "${driver_dir}" ]] || [[ ! -d "${libfprint_root}/builddir" ]]; then
      echo -e "${C_YELLOW}First-time host setup — integrating driver and building...${C_RESET}"
      LIBFPRINT_DIR="${libfprint_root}" bash "${setup_script}" --integrate --build
    else
      cp "${PROJECT_ROOT}/src/canvasbio_cb2000.c" "${driver_dir}/"
      cp "${PROJECT_ROOT}/src/cb2000_sigfm_matcher.c" "${driver_dir}/"
      cp "${PROJECT_ROOT}/src/cb2000_sigfm_matcher.h" "${driver_dir}/"
      (cd "${libfprint_root}" && ninja -C builddir)
    fi
  fi
}

# ─── Options 5/6: Session ─────────────────────────────────────────────────────
run_session() {
  local do_build="${1:-0}"
  echo ""
  echo -e "${C_BOLD}=== Interactive Session ===${C_RESET}"

  if [[ "${do_build}" == "1" ]]; then
    echo "Running builds before session..."
    build_opencv_helper
    build_libfprint
  fi

  export CB2000_LOG_ROOT DBX_NAME CB2000_LIBFPRINT_ROOT BUILD_TARGET

  if [[ "${BUILD_TARGET}" == "container" ]]; then
    bash "${SCRIPTS_DIR}/run_cb2000_interactive.sh"
  else
    bash "${SCRIPTS_DIR}/run_cb2000_interactive.sh" --no-container
  fi
}

# ─── Option 7: Battery report ─────────────────────────────────────────────────
battery_report() {
  echo ""
  echo -e "${C_BOLD}=== Battery Report ===${C_RESET}"
  export CB2000_LOG_ROOT
  bash "${SCRIPTS_DIR}/battery_report.sh" "$@"
}

# ─── Main loop ────────────────────────────────────────────────────────────────
main() {
  load_env

  while true; do
    print_header
    read -r -p "Choice [1-7/Q]: " choice
    case "${choice}" in
      1) configure_env; load_env ;;
      2) setup_venv ;;
      3) build_opencv_helper ;;
      4) build_libfprint ;;
      5) run_session 1 ;;
      6) run_session 0 ;;
      7) battery_report ;;
      [Qq]) echo "Exiting."; exit 0 ;;
      *) echo -e "${C_YELLOW}Invalid option.${C_RESET}" ;;
    esac
    echo ""
    read -r -p "Press Enter to continue..."
  done
}

main "$@"
